{
    'name': 'Monal Employee OutWard GatePass',
    'version': '18.0',
    'category': 'Extra Tools',
    'summary': 'Module for managing the Employee OutWard GatePass information',
    'sequence': '-1005',
    'license': 'AGPL-3',
    'author': 'HASNAIN JUTT(GXS)',
    'Maintainer': 'Odoo',
    'website': 'odoomates.com',
    'depends': ['hr', 'hr_contract', 'base', 'hr_attendance'],
    'demo': [],
    'data': [
        # 'data/seq_num_resignation.xml',
        'security/ir.model.access.csv',
        'views/employee_gatepass.xml',
        'views/outward_gatpass_pdf.xml',
        # 'views/notice_type.xml',
        # 'views/portal/portal_view.xml',
    ],
    'installable': True,
    'application': True,
    'auto install': False,
}
