{
    'name': 'Monal Leaves Enchasment',
    'version': '18.0',
    'category': 'Extra Tools',
    'summary': 'Module for managing the Leave Encashment',
    'sequence': '-1000',
    'license': 'AGPL-3',
    'author': ' Hammad Asghar,',
    'Maintainer': 'Odoo Mates',
    'website': 'odoomates.com',
    'depends': ['hr','hr_holidays'],
    # 'depends': ['hr','hr_holidays','monal_period','monal_weekly_off'],
    'demo': [],
    'data': [
        'security/ir.model.access.csv',
        # 'security/leave_encashment_rules.xml',
        'views/hr_leave_type.xml',
        'views/view.xml',
        'wizard/bulk_leave_encashment.xml',
    ],
    'installable': True,
    'application': True,
    'auto install': False,
}
